language: rust
sudo: false

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  include:
  # Builds on nightly.
  - os: linux
    rust: nightly
    env: RUST_BACKTRACE=1
    install:
      - cargo install wasm-pack --force #todo improve this, it's very slow
    before_script:
      - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      - wasm-pack build && cd www && npm install
    script:
      - cargo check
      - cargo check --target wasm32-unknown-unknown
      - cargo check                                 --no-default-features
      - cargo check --target wasm32-unknown-unknown --no-default-features
      - cargo check                                 --no-default-features --features console_error_panic_hook
      - cargo check --target wasm32-unknown-unknown --no-default-features --features console_error_panic_hook
      - cargo check                                 --no-default-features --features "console_error_panic_hook wee_alloc"
      - cargo check --target wasm32-unknown-unknown --no-default-features --features "console_error_panic_hook wee_alloc"
      - export CARGO_INCREMENTAL=0
      - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
      - cargo build --verbose $CARGO_OPTIONS
      - cargo test --verbose $CARGO_OPTIONS
      - find . \( -name "big_primes*.gc*" \) -print
      - |
        zip -0 ccov.zip `find . \( -name "big_primes*.gc*" \) -print`;
        ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info;
        bash <(curl -s https://codecov.io/bash) -f lcov.info;
  # Builds on beta.
  - os: linux
    rust: beta
    env: RUST_BACKTRACE=1
    install:
      - cargo install wasm-pack --force #todo improve this, it's very slow
    before_script:
      - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      - wasm-pack build && cd www && npm install
    script:
      - cargo check
      - cargo check --target wasm32-unknown-unknown
      - cargo check                                 --no-default-features
      - cargo check --target wasm32-unknown-unknown --no-default-features
      - cargo check                                 --no-default-features --features console_error_panic_hook
      - cargo check --target wasm32-unknown-unknown --no-default-features --features console_error_panic_hook
      # Note: no enabling the `wee_alloc` feature here because it requires
      # nightly for now.
  # Builds on stable.
  - os: linux
    rust: stable
    env: RUST_BACKTRACE=1
    install:
      - cargo install wasm-pack --force #todo improve this, it's very slow
    before_script:
      - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      - wasm-pack build && cd www && npm install
    script:
      - cargo check
      - cargo check --target wasm32-unknown-unknown
      - cargo check                                 --no-default-features
      - cargo check --target wasm32-unknown-unknown --no-default-features
      - cargo check                                 --no-default-features --features console_error_panic_hook
      - cargo check --target wasm32-unknown-unknown --no-default-features --features console_error_panic_hook
      # Note: no enabling the `wee_alloc` feature here because it requires
      # nightly for now.

after_success:
  - #TODO: Deploy!
  - #aws s3 sync htdocs/. s3://frontend.bigprimes.net --exact-timestamps --delete --exclude ".git/*"
  - #aws cloudfront create-invalidation --distribution-id xxxxxxxxxx --paths "/*"
  - #bash <(curl -s https://codecov.io/bash)

notifications:
  email: false