name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { toolchain: stable }
          - { toolchain: beta }
          - { toolchain: nightly }

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Lint code ${{ matrix.config.toolchain }}
        run: |
          rustup toolchain install ${{ matrix.config.toolchain }}
          rustup default ${{ matrix.config.toolchain }}
          rustup component add rustfmt
          cargo fmt --all -- --check

  test:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { toolchain: nightly }

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run tests ${{ matrix.config.toolchain }}
        run: |
          rustup toolchain install ${{ matrix.config.toolchain }}
          rustup default ${{ matrix.config.toolchain }}
          cargo test --verbose

  bench:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { toolchain: nightly }

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run benchmarks ${{ matrix.config.toolchain }}
        run: |
          rustup toolchain install ${{ matrix.config.toolchain }}
          rustup default ${{ matrix.config.toolchain }}
          cargo bench bench
